# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bek_format.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'bek_format.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x62\x65k_format.proto\x12\nbek_format\"\xe1\x03\n\x18\x43ompressedGeometryHeader\x12\x14\n\x0cvertex_count\x18\x01 \x01(\r\x12\x12\n\nblock_size\x18\x02 \x01(\r\x12\x10\n\x08hop_size\x18\x0b \x01(\r\x12\x12\n\nsort_min_x\x18\x03 \x01(\x02\x12\x12\n\nsort_max_x\x18\x04 \x01(\x02\x12\x12\n\nsort_min_y\x18\x05 \x01(\x02\x12\x12\n\nsort_max_y\x18\x06 \x01(\x02\x12\x12\n\nsort_min_z\x18\x07 \x01(\x02\x12\x12\n\nsort_max_z\x18\x08 \x01(\x02\x12>\n\x15uncompressed_channels\x18\t \x03(\x0b\x32\x1f.bek_format.UncompressedChannel\x12:\n\x13\x63ompressed_channels\x18\n \x03(\x0b\x32\x1d.bek_format.CompressedChannel\x12\x38\n\x12quantized_channels\x18\x0c \x03(\x0b\x32\x1c.bek_format.QuantizedChannel\x12\x41\n\x17vector_quantized_groups\x18\x0e \x03(\x0b\x32 .bek_format.VectorQuantizedGroup\x12\x18\n\x10\x64ropped_channels\x18\r \x03(\t\"@\n\x13UncompressedChannel\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x64type\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\"n\n\x11\x43ompressedChannel\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x64type\x18\x02 \x01(\t\x12\x1a\n\x12quantization_array\x18\x03 \x03(\x02\x12 \n\x18\x61rithmetic_payload_bytes\x18\x04 \x01(\x04\"P\n\x10QuantizedChannel\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07min_val\x18\x02 \x01(\x01\x12\x0f\n\x07max_val\x18\x03 \x01(\x01\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\x0c\"P\n\x14VectorQuantizedGroup\x12\x15\n\rchannel_names\x18\x01 \x03(\t\x12\x10\n\x08\x63odebook\x18\x02 \x01(\x0c\x12\x0f\n\x07indices\x18\x03 \x01(\x0c\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bek_format_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMPRESSEDGEOMETRYHEADER']._serialized_start=33
  _globals['_COMPRESSEDGEOMETRYHEADER']._serialized_end=514
  _globals['_UNCOMPRESSEDCHANNEL']._serialized_start=516
  _globals['_UNCOMPRESSEDCHANNEL']._serialized_end=580
  _globals['_COMPRESSEDCHANNEL']._serialized_start=582
  _globals['_COMPRESSEDCHANNEL']._serialized_end=692
  _globals['_QUANTIZEDCHANNEL']._serialized_start=694
  _globals['_QUANTIZEDCHANNEL']._serialized_end=774
  _globals['_VECTORQUANTIZEDGROUP']._serialized_start=776
  _globals['_VECTORQUANTIZEDGROUP']._serialized_end=856
# @@protoc_insertion_point(module_scope)
